### ISSUE TITLE
Bug: Multi Robot: AMCL

### ISSUE THREAD

**Issue by johSchm** [ovgu-FINken/multi_robot_path_planning#1]
After running the start script (multi_robo.sh):

ERROR: cannot launch node of type [amcl/amcl]: amcl
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/johschm/git/DrivingSwarm/src
ROS path [2]=/opt/ros/melodic/share

**Comment by Travellerer** [comment]
ros clean install of packages following steps 1.2 to 1.4. of ros install for ubuntu

workspace newly built with catkin
