### ISSUE TITLE
Research on map presentations

### ISSUE THREAD

**Issue by ntraichel** [ovgu-FINken/multi_robot_path_planning#19]
Collecting possible map presentations, explaining disadvantages and advantages of each of them.

**Comment by IffatJamil** [comment]
[Capturing connectivity Cfree into a graph.pdf](https://github.com/ovgu-FINken/multi_robot_path_planning/files/4034956/Capturing.connectivity.Cfree.into.a.graph.pdf)
[Uploading Voronoi Graph in ROS.pdf…]()

**Comment by ntraichel** [comment]
see wiki
