### ISSUE TITLE
Bug: Multi Robot: Map Server

### ISSUE THREAD

**Issue by johSchm** [ovgu-FINken/multi_robot_path_planning#2]
ERROR: cannot launch node of type [map_server/map_server]: map_server
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/johschm/git/DrivingSwarm/src
ROS path [2]=/opt/ros/melodic/share
process[tb3_0/inital_pose_publisher-2]: started with pid [11926]

**Comment by Travellerer** [comment]
ros clean install of packages following steps 1.2 to 1.4. of ros install for ubuntu

workspace newly built with catkin
