### ISSUE TITLE
Bug: Multi Robot: Move Base

### ISSUE THREAD

**Issue by johSchm** [ovgu-FINken/multi_robot_path_planning#3]
ERROR: cannot launch node of type [move_base/move_base]: move_base
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/johschm/git/DrivingSwarm/src
ROS path [2]=/opt/ros/melodic/share

**Comment by Travellerer** [comment]
ros clean install of packages following steps 1.2 to 1.4. of ros install for ubuntu

workspace newly built with catkin
