### ISSUE TITLE
Bug: Multi Robot: Follower

### ISSUE THREAD

**Issue by johSchm** [ovgu-FINken/multi_robot_path_planning#4]
Traceback (most recent call last):
  File "/home/johschm/git/DrivingSwarm/src/pathplanning/multi_robot/nodes/follower.py", line 8, in <module>
    import scipy.stats
ImportError: No module named scipy.stats

[tb3_0/follower-3] process has died [pid 12163, exit code 1, cmd /home/johschm/git/DrivingSwarm/src/pathplanning/multi_robot/nodes/follower.py __name:=follower __log:=/home/johschm/.ros/log/5f66a550-03d7-11ea-9554-303a6419c0bc/tb3_0-follower-3.log].
log file: /home/johschm/.ros/log/5f66a550-03d7-11ea-9554-303a6419c0bc/tb3_0-follower-3*.log

**Comment by bastinat0r** [comment]
Installing the right packages and rebuilding resolves the Problem.
